title: vez
frequency: 3
dirfilter:
- tmp
- .git
- .github
- assets
- public
- scripts
- vendor
- logs
ext:
- go
- tmpl
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
  - go mod tidy
  - go mod vendor
  after:
  - ps -ef|grep 'vez web'| grep -v grep | awk '{print $2}' | xargs kill -9 
  - ps -ef|grep 'vez robot'| grep -v grep | awk '{print $2}' | xargs kill -9 
  -  ./vez web &
  -  ./vez robot &
  exit:
  - ps -ef|grep 'vez web'| grep -v grep
  - ps -ef|grep 'vez web'| grep -v grep | awk '{print $2}' | xargs kill -9
  - ps -ef|grep 'vez robot'| grep -v grep
  - ps -ef|grep 'vez robot'| grep -v grep | awk '{print $2}' | xargs kill -9 
  - rm -rf ./vez
link: https://github.com/midoks/zzz
